export default defineAppConfig({
  pages: [
    "pages/home/index",
    "pages/schedule/index",
    "pages/standings/index",
    "pages/data/index",
    "pages/mine/index",
    "pages/auth/index",
    "pages/leader-register/index",
    "pages/admin-register/index",
    "pages/leader/index",
    "pages/reschedule-create/index",
    "pages/reschedule-requests/index",
    "pages/special-reschedule/index",
    "pages/admin/index",
    "pages/admin-games/index",
    "pages/game-media/index",
  ],
  subPackages: [
    {
      root: "scoresheet",
      pages: ["pages/list/index", "pages/editor/index"],
    },
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#faf9f6",
    navigationBarTitleText: "PKUBA",
    navigationBarTextStyle: "black",
    backgroundColor: "#f2f0eb",
  },
  tabBar: {
    custom: true,
    color: "#76716a",
    selectedColor: "#c91f26",
    backgroundColor: "#faf9f6",
    borderStyle: "black",
    list: [
      { pagePath: "pages/home/index", text: "首页" },
      { pagePath: "pages/schedule/index", text: "对阵" },
      { pagePath: "pages/standings/index", text: "排名" },
      { pagePath: "pages/data/index", text: "数据" },
      { pagePath: "pages/mine/index", text: "我的" },
    ],
  },
});
