# Generated by Django 5.2.17 on 2026-08-18 19:58

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EmailOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', '待发送'), ('SENDING', '发送中'), ('SENT', '已发送'), ('FAILED', '失败')], default='PENDING', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=16)),
                ('name', models.CharField(max_length=40)),
                ('start_time', models.TimeField()),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(choices=[('USER', '普通用户'), ('ADMIN', '普通管理员'), ('SUPERADMIN', '超级管理员')], default='USER', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=96)),
                ('object_type', models.CharField(max_length=64)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('before', models.JSONField(default=dict)),
                ('after', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registered_via_shared_secret', models.BooleanField(default=False)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
                ('promoted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promoted_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CompetitionGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=16)),
                ('name', models.CharField(max_length=40)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='core.division')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InboxItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField(blank=True)),
                ('object_type', models.CharField(blank=True, max_length=64)),
                ('object_id', models.UUIDField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbox_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParticipantSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=80)),
                ('seed', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participant_slots', to='core.division')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participant_slots', to='core.competitiongroup')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('stage', models.CharField(choices=[('GROUP', '小组赛'), ('ROUND_ROBIN', '循环赛'), ('KNOCKOUT', '淘汰赛'), ('SEMIFINAL', '半决赛'), ('FINAL', '决赛'), ('RELEGATION', '保级赛')], default='GROUP', max_length=20)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('date', models.DateField()),
                ('leader_adjustable', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('SCHEDULED', '未赛'), ('COMPLETED', '已完成'), ('FORFEIT', '弃权'), ('VOID', '已作废')], default='SCHEDULED', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='core.division')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='core.competitiongroup')),
                ('away_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='core.participantslot')),
                ('home_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='core.participantslot')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='core.period')),
            ],
            options={
                'ordering': ['date', 'period__sort_order', 'venue__sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RescheduleRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('SAME_WEEK', '同周'), ('CROSS_WEEK', '跨周')], max_length=16)),
                ('status', models.CharField(choices=[('WAITING_OPPONENT', '等待对手'), ('WAITING_ADMIN_DECISION', '等待管理员决定'), ('WAITING_SELECTED_TEAMS', '等待指定球队'), ('WAITING_ADMIN_FINAL', '等待管理员终审'), ('APPROVED', '通过'), ('REJECTED', '拒绝'), ('WITHDRAWN', '撤回'), ('EXPIRED', '过期'), ('ADMIN_CANCELLED', '管理员取消')], default='WAITING_OPPONENT', max_length=32)),
                ('target_date', models.DateField()),
                ('original_game_snapshot', models.JSONField()),
                ('game_version_at_submit', models.PositiveIntegerField()),
                ('submit_deadline', models.DateTimeField()),
                ('confirmation_deadline', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='core.game')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to=settings.AUTH_USER_MODEL)),
                ('target_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='core.period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='active_reschedule_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='locked_games', to='core.reschedulerequest'),
        ),
        migrations.CreateModel(
            name='ScheduleImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('UPLOADED', '已上传'), ('VALIDATED', '已校验'), ('CONFIRMED', '已确认'), ('REJECTED', '已拒绝')], default='UPLOADED', max_length=16)),
                ('template_version', models.CharField(max_length=32)),
                ('file_key', models.CharField(max_length=512)),
                ('file_sha256', models.CharField(max_length=64)),
                ('summary', models.JSONField(default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImportIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('severity', models.CharField(choices=[('ERROR', '错误'), ('WARNING', '警告')], max_length=16)),
                ('code', models.CharField(max_length=64)),
                ('cell', models.CharField(blank=True, max_length=32)),
                ('message', models.TextField()),
                ('context', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='core.scheduleimportbatch')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('competition_type', models.CharField(choices=[('PKU_CUP', '北大杯'), ('FRESHMAN_CUP', '新生杯')], max_length=24)),
                ('year', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('SETUP', '准备中'), ('PRE_DRAW_PUBLIC', '抽签前公开'), ('ACTIVE', '进行中'), ('ARCHIVED', '已归档')], default='SETUP', max_length=24)),
                ('is_public', models.BooleanField(default=False, editable=False)),
                ('timezone', models.CharField(default='Asia/Shanghai', max_length=64)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['-year', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_public', True)), fields=('is_public',), name='only_one_public_season'), models.CheckConstraint(condition=models.Q(models.Q(('is_public', True), ('status__in', ['PRE_DRAW_PUBLIC', 'ACTIVE'])), models.Q(('is_public', False), ('status__in', ['SETUP', 'ARCHIVED'])), _connector='OR'), name='season_public_matches_status'), models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='season_dates_ordered')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlotLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_locks', to='core.period')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='slot_locks', to='core.season')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleimportbatch',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_imports', to='core.season'),
        ),
        migrations.CreateModel(
            name='PeriodCapacity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(help_text='Monday=0, Sunday=6')),
                ('capacity', models.PositiveSmallIntegerField(default=0)),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacities', to='core.period')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capacities', to='core.season')),
            ],
            options={
                'ordering': ['weekday', 'period__sort_order'],
            },
        ),
        migrations.AddField(
            model_name='period',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='core.season'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='core.season'),
        ),
        migrations.AddField(
            model_name='division',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='divisions', to='core.season'),
        ),
        migrations.CreateModel(
            name='SlotReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', '有效'), ('CONVERTED', '已转换'), ('RELEASED', '已释放')], default='ACTIVE', max_length=16)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('converted_game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='converted_reservations', to='core.game')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.period')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.season')),
            ],
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='reservation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='request', to='core.slotreservation'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('short_name', models.CharField(blank=True, max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='core.division')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='core.season')),
            ],
            options={
                'ordering': ['division__sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeasonLeaderBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leader_name', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader_bindings', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader_bindings', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leader_bindings', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='RosterPlayer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('role', models.CharField(default='PLAYER', max_length=32)),
                ('eligible', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
                ('private_note', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roster', to='core.team')),
            ],
            options={
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='requester_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='core.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='away_games', to='core.team'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='home_games', to='core.team'),
        ),
        migrations.CreateModel(
            name='DrawAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='assignment', to='core.participantslot')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draw_assignments', to='core.season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='draw_assignments', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('OPPONENT', '对手确认'), ('VOTER', '指定球队投票')], max_length=16)),
                ('response', models.CharField(choices=[('PENDING', '待处理'), ('ACCEPTED', '同意'), ('REJECTED', '拒绝')], default='PENDING', max_length=16)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='core.reschedulerequest')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmations', to='core.team')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='venues', to='core.season')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='slotreservation',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='core.venue'),
        ),
        migrations.AddField(
            model_name='reschedulerequest',
            name='target_venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reschedule_requests', to='core.venue'),
        ),
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='core.venue'),
        ),
        migrations.CreateModel(
            name='WebLoginChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeChatIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(max_length=64)),
                ('openid', models.CharField(max_length=128)),
                ('unionid', models.CharField(blank=True, max_length=128)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wechat_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='competitiongroup',
            constraint=models.UniqueConstraint(fields=('division', 'code'), name='uniq_group_code'),
        ),
        migrations.AddConstraint(
            model_name='participantslot',
            constraint=models.UniqueConstraint(fields=('division', 'code'), name='uniq_slot_code'),
        ),
        migrations.AddConstraint(
            model_name='scheduleslotlock',
            constraint=models.UniqueConstraint(fields=('season', 'date', 'period'), name='uniq_schedule_slot_lock'),
        ),
        migrations.AddConstraint(
            model_name='periodcapacity',
            constraint=models.UniqueConstraint(fields=('season', 'weekday', 'period'), name='uniq_period_capacity'),
        ),
        migrations.AddConstraint(
            model_name='periodcapacity',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='weekday_zero_to_six'),
        ),
        migrations.AddConstraint(
            model_name='period',
            constraint=models.UniqueConstraint(fields=('season', 'code'), name='uniq_period_code'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('season', 'code'), name='uniq_division_code'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('division', 'name'), name='uniq_team_in_division'),
        ),
        migrations.AddConstraint(
            model_name='seasonleaderbinding',
            constraint=models.UniqueConstraint(fields=('season', 'account'), name='uniq_leader_account_per_season'),
        ),
        migrations.AddConstraint(
            model_name='seasonleaderbinding',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='uniq_leader_team_per_season'),
        ),
        migrations.AddConstraint(
            model_name='drawassignment',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='uniq_draw_team_per_season'),
        ),
        migrations.AddConstraint(
            model_name='teamconfirmation',
            constraint=models.UniqueConstraint(fields=('request', 'team', 'purpose'), name='uniq_team_confirmation'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('season', 'code'), name='uniq_venue_code'),
        ),
        migrations.AddConstraint(
            model_name='slotreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('season', 'date', 'period', 'venue'), name='uniq_active_reservation_venue'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(fields=('season', 'code'), name='uniq_game_code'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'VOID'), _negated=True), fields=('season', 'date', 'period', 'venue'), name='uniq_active_game_venue_slot'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('home_team', models.F('away_team')), _negated=True), name='game_distinct_teams'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('home_slot', models.F('away_slot')), _negated=True), name='game_distinct_slots'),
        ),
        migrations.AddConstraint(
            model_name='wechatidentity',
            constraint=models.UniqueConstraint(fields=('app_id', 'openid'), name='uniq_wechat_app_openid'),
        ),
    ]
