# Generated by Django 5.2.17 on 2026-08-19 07:18

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import uuid
from django.conf import settings
from django.contrib.auth.hashers import make_password
from django.db import migrations, models


def populate_identity_defaults(apps, schema_editor):
    del schema_editor
    Season = apps.get_model('core', 'Season')
    Division = apps.get_model('core', 'Division')
    now = django.utils.timezone.now()
    for season in Season.objects.filter(admin_invite_code_hash=''):
        season.admin_invite_code_hash = make_password('PKUBA1997')
        season.admin_invite_updated_at = now
        season.save(update_fields=['admin_invite_code_hash', 'admin_invite_updated_at'])
    Division.objects.filter(name__startswith='女').update(gender='WOMEN')


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniAppSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WeChatAuthTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_id', models.CharField(max_length=64)),
                ('openid', models.CharField(max_length=128)),
                ('unionid', models.CharField(blank=True, max_length=128)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='account',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='seasonleaderbinding',
            name='leader_name',
        ),
        migrations.AddField(
            model_name='division',
            name='gender',
            field=models.CharField(choices=[('MEN', '男篮'), ('WOMEN', '女篮')], default='MEN', max_length=8),
        ),
        migrations.AddField(
            model_name='season',
            name='admin_invite_code_hash',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='season',
            name='admin_invite_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='admin_invite_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_season_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_identity_defaults, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='uniq_account_username_ci'),
        ),
        migrations.AddField(
            model_name='miniappsession',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miniapp_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
