# Generated by Django 5.2.17 on 2026-08-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_miniappsession_wechatauthticket_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
