# Generated by Django 5.2.17 on 2026-08-19 07:51

import core.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_account_email_remove_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', core.models.AccountManager()),
            ],
        ),
    ]
