# Generated by Django 5.2.17 on 2026-08-19 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='away_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='home_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('away_score__isnull', True), ('home_score__isnull', True)), models.Q(('away_score__isnull', False), ('home_score__isnull', False)), _connector='OR'), name='game_scores_both_set_or_null'),
        ),
        migrations.AddConstraint(
            model_name='game',
            constraint=models.CheckConstraint(condition=models.Q(('home_score__isnull', True), models.Q(('home_score', models.F('away_score')), _negated=True), _connector='OR'), name='game_official_score_not_tied'),
        ),
    ]
