# Generated by Django 5.2 for PKUBA.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_game_away_score_game_home_score_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameMediaAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("SCORESHEET", "记录表"), ("GAME_PHOTO", "比赛照片")],
                        max_length=20,
                    ),
                ),
                ("file_key", models.CharField(max_length=512, unique=True)),
                ("original_filename", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=80)),
                ("file_sha256", models.CharField(max_length=64)),
                ("byte_size", models.PositiveIntegerField()),
                ("width", models.PositiveIntegerField()),
                ("height", models.PositiveIntegerField()),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("scoresheet_complete_confirmed", models.BooleanField(default=False)),
                (
                    "review_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待审核"),
                            ("APPROVED", "已通过"),
                            ("REJECTED", "未通过"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("review_note", models.CharField(blank=True, max_length=300)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deleted_game_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="media_assets",
                        to="core.game",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_game_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_game_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "sort_order", "created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="gamemediaasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("game", "kind", "file_sha256"),
                name="uniq_active_game_media_hash",
            ),
        ),
        migrations.AddConstraint(
            model_name="gamemediaasset",
            constraint=models.CheckConstraint(
                condition=(
                    ~models.Q(("kind", "SCORESHEET"))
                    | models.Q(("scoresheet_complete_confirmed", True))
                ),
                name="scoresheet_requires_complete_confirmation",
            ),
        ),
    ]
