# Generated by Django 5.2 for PKUBA.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_gamemediaasset"),
    ]

    operations = [
        migrations.AddField(
            model_name="competitiongroup",
            name="created_by_import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_groups",
                to="core.scheduleimportbatch",
            ),
        ),
        migrations.AddField(
            model_name="participantslot",
            name="created_by_import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_slots",
                to="core.scheduleimportbatch",
            ),
        ),
        migrations.AddField(
            model_name="game",
            name="created_by_import_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_games",
                to="core.scheduleimportbatch",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleimportbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "已上传"),
                    ("VALIDATED", "已校验"),
                    ("CONFIRMED", "已确认"),
                    ("REJECTED", "已拒绝"),
                    ("ROLLED_BACK", "已回滚"),
                ],
                default="UPLOADED",
                max_length=16,
            ),
        ),
    ]
