# Generated by Django 5.2.17 on 2026-08-21 09:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schedule_grid_drafts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePlayerStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('player_name', models.CharField(max_length=80)),
                ('jersey_number', models.CharField(blank=True, max_length=2)),
                ('appeared', models.BooleanField(default=False)),
                ('starter', models.BooleanField(default=False)),
                ('points', models.PositiveSmallIntegerField(default=0)),
                ('one_point_events', models.PositiveSmallIntegerField(default=0)),
                ('two_point_events', models.PositiveSmallIntegerField(default=0)),
                ('three_point_events', models.PositiveSmallIntegerField(default=0)),
                ('personal_fouls', models.PositiveSmallIntegerField(default=0)),
                ('foul_types', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='GameScoresheet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_version', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('NO_SOURCE', '缺少原图'), ('RECOGNITION_QUEUED', '等待识别'), ('RECOGNIZING', '识别中'), ('RETRY_WAIT', '等待重试'), ('DRAFT', '人工核对'), ('RECOGNITION_FAILED', '识别失败'), ('READY', '可以发布'), ('PUBLISHED', '已发布')], default='NO_SOURCE', max_length=32)),
                ('draft', models.JSONField(default=dict)),
                ('draft_version', models.PositiveIntegerField(default=1)),
                ('event_sequence', models.PositiveBigIntegerField(default=0)),
                ('game_prior_snapshot', models.JSONField(default=dict)),
                ('roster_snapshot', models.JSONField(default=dict)),
                ('reviewed_regions', models.JSONField(default=dict)),
                ('validation_report', models.JSONField(default=dict)),
                ('validation_draft_version', models.PositiveIntegerField(blank=True, null=True)),
                ('acknowledged_warnings', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GameTeamStat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('side', models.CharField(max_length=1)),
                ('period_scores', models.JSONField(default=list)),
                ('total_score', models.PositiveSmallIntegerField()),
                ('won', models.BooleanField(default=False)),
                ('timeouts', models.JSONField(default=dict)),
                ('team_fouls', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ScoresheetChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_sequence', models.PositiveBigIntegerField()),
                ('draft_version', models.PositiveIntegerField()),
                ('event_type', models.CharField(max_length=48)),
                ('client_id', models.CharField(blank=True, max_length=96)),
                ('surface', models.CharField(blank=True, max_length=16)),
                ('changed_fields', models.JSONField(default=list)),
                ('payload', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['scoresheet', 'event_sequence'],
            },
        ),
        migrations.CreateModel(
            name='ScoresheetEditLease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('client_id', models.CharField(max_length=96)),
                ('surface', models.CharField(choices=[('WEB', '网页'), ('MINIAPP', '小程序')], max_length=16)),
                ('last_heartbeat_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ScoresheetPublication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publication_number', models.PositiveIntegerField()),
                ('draft_version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('validation_report', models.JSONField()),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['scoresheet', 'publication_number'],
            },
        ),
        migrations.CreateModel(
            name='ScoresheetRecognitionRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('QUEUED', '等待识别'), ('RUNNING', '识别中'), ('RETRY_WAIT', '等待重试'), ('SUCCEEDED', '识别成功'), ('FAILED', '识别失败'), ('STOPPED', '已停止'), ('SUPERSEDED', '已被新原图替代')], default='QUEUED', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=4)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('provider_run_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('provider_result', models.JSONField(default=dict)),
                ('provider_usage', models.JSONField(default=dict)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('last_error', models.TextField(blank=True)),
                ('worker_lease_token', models.UUIDField(blank=True, null=True)),
                ('worker_lease_owner', models.CharField(blank=True, max_length=96)),
                ('worker_lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('stopped_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoresheetRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('draft_version', models.PositiveIntegerField()),
                ('event_sequence', models.PositiveBigIntegerField()),
                ('reason', models.CharField(choices=[('SOURCE_REPLACED', '替换原图'), ('RECOGNITION_APPLIED', '应用识别'), ('EXPLICIT_SAVE', '显式保存'), ('VALIDATION_READY', '校验就绪'), ('PUBLISHED', '发布')], max_length=32)),
                ('snapshot', models.JSONField()),
                ('client_id', models.CharField(blank=True, max_length=96)),
                ('surface', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'ordering': ['scoresheet', 'draft_version', 'created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='gamemediaasset',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('kind', 'SCORESHEET')), fields=('game',), name='uniq_active_scoresheet_per_game'),
        ),
        migrations.AddField(
            model_name='gameplayerstat',
            name='roster_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_stats', to='core.rosterplayer'),
        ),
        migrations.AddField(
            model_name='gameplayerstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_game_stats', to='core.team'),
        ),
        migrations.AddField(
            model_name='gamescoresheet',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scoresheet', to='core.game'),
        ),
        migrations.AddField(
            model_name='gamescoresheet',
            name='source_asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoresheet_sources', to='core.gamemediaasset'),
        ),
        migrations.AddField(
            model_name='gameteamstat',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_stats', to='core.team'),
        ),
        migrations.AddField(
            model_name='scoresheetchangelog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoresheet_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheetchangelog',
            name='scoresheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_logs', to='core.gamescoresheet'),
        ),
        migrations.AddField(
            model_name='scoresheeteditlease',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoresheet_edit_leases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheeteditlease',
            name='scoresheet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='edit_lease', to='core.gamescoresheet'),
        ),
        migrations.AddField(
            model_name='scoresheetpublication',
            name='published_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoresheet_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheetpublication',
            name='scoresheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='core.gamescoresheet'),
        ),
        migrations.AddField(
            model_name='scoresheetpublication',
            name='source_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoresheet_publications', to='core.gamemediaasset'),
        ),
        migrations.AddField(
            model_name='scoresheetpublication',
            name='supersedes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='superseded_by', to='core.scoresheetpublication'),
        ),
        migrations.AddField(
            model_name='gameteamstat',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_stats', to='core.scoresheetpublication'),
        ),
        migrations.AddField(
            model_name='gamescoresheet',
            name='current_publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_for_scoresheets', to='core.scoresheetpublication'),
        ),
        migrations.AddField(
            model_name='gameplayerstat',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_stats', to='core.scoresheetpublication'),
        ),
        migrations.AddField(
            model_name='scoresheetrecognitionrun',
            name='scoresheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_runs', to='core.gamescoresheet'),
        ),
        migrations.AddField(
            model_name='scoresheetrecognitionrun',
            name='source_asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognition_runs', to='core.gamemediaasset'),
        ),
        migrations.AddField(
            model_name='scoresheetrecognitionrun',
            name='stopped_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stopped_scoresheet_recognitions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheetrevision',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoresheet_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scoresheetrevision',
            name='scoresheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='core.gamescoresheet'),
        ),
        migrations.AddConstraint(
            model_name='scoresheetchangelog',
            constraint=models.UniqueConstraint(fields=('scoresheet', 'event_sequence'), name='uniq_scoresheet_change_event'),
        ),
        migrations.AddIndex(
            model_name='scoresheeteditlease',
            index=models.Index(fields=['expires_at'], name='core_scores_expires_990127_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoresheetpublication',
            constraint=models.UniqueConstraint(fields=('scoresheet', 'publication_number'), name='uniq_scoresheet_publication_number'),
        ),
        migrations.AddConstraint(
            model_name='gameteamstat',
            constraint=models.UniqueConstraint(fields=('publication', 'team'), name='uniq_publication_team_stat'),
        ),
        migrations.AddConstraint(
            model_name='gameteamstat',
            constraint=models.CheckConstraint(condition=models.Q(('side__in', ['A', 'B'])), name='team_stat_side'),
        ),
        migrations.AddConstraint(
            model_name='gameplayerstat',
            constraint=models.UniqueConstraint(condition=models.Q(('roster_player__isnull', False)), fields=('publication', 'team', 'roster_player'), name='uniq_publication_roster_player_stat'),
        ),
        migrations.AddIndex(
            model_name='scoresheetrecognitionrun',
            index=models.Index(fields=['status', 'next_attempt_at', 'created_at'], name='core_scores_status_d90204_idx'),
        ),
        migrations.AddIndex(
            model_name='scoresheetrecognitionrun',
            index=models.Index(fields=['worker_lease_expires_at'], name='core_scores_worker__89cf00_idx'),
        ),
        migrations.AddConstraint(
            model_name='scoresheetrecognitionrun',
            constraint=models.UniqueConstraint(fields=('scoresheet', 'source_version'), name='uniq_scoresheet_recognition_source'),
        ),
        migrations.AddConstraint(
            model_name='scoresheetrecognitionrun',
            constraint=models.CheckConstraint(condition=models.Q(('max_attempts', 4)), name='scoresheet_recognition_four_attempts'),
        ),
        migrations.AddConstraint(
            model_name='scoresheetrecognitionrun',
            constraint=models.CheckConstraint(condition=models.Q(('attempt_count__lte', 4)), name='scoresheet_recognition_attempt_limit'),
        ),
        migrations.AddConstraint(
            model_name='scoresheetrevision',
            constraint=models.UniqueConstraint(fields=('scoresheet', 'event_sequence'), name='uniq_scoresheet_revision_event'),
        ),
    ]
