# Generated by Django 5.2.12 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_workerheartbeat"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rosterplayer",
            constraint=models.UniqueConstraint(
                condition=models.Q(active=True) & ~models.Q(jersey_number=""),
                fields=("team", "jersey_number"),
                name="uniq_active_roster_jersey_per_team",
            ),
        ),
    ]
